version: '3'
services:
#    composer:
#        image: composer:1.8
#        volumes:
#            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
#        working_dir: ${APP_PATH_CONTAINER}
#        volumes_from:
#            - php
#        links:
#            - nginx
#            - php
#        command: 'cd ${PROJECT_NAME} && /usr/bin/composer install --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader'

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - 8000:80
        working_dir: ${APP_PATH_CONTAINER}
        volumes:
            - ${NGINX_PATH_CONF_HOST}:${NGINX_PATH_CONF_CONTAINER}
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        links:
            - php

    php:
        build: ./php
        environment:
            TIMEZONE: Europe/Moskow
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: 'rm -rf ${PROJECT_NAME} && git clone https://github.com/rus-lan/image-optimizer.git ${PROJECT_NAME}'
