version: '3'
services:
    composer:
        image: composer:latest
        expose:
            - 9000
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: "cd ${PROJECT_NAME} && composer install --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader"
        links:
            - nginx
        extra_hosts:
            - "docker-host.localhost:127.0.0.1"

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - 8080:80
        working_dir: ${APP_PATH_CONTAINER}
        volumes:
            - ${NGINX_PATH_CONF_HOST}:${NGINX_PATH_CONF_CONTAINER}
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        links:
            - php
        command: "service nginx restart"

    php:
        build: ./php
        environment:
            TIMEZONE: Europe/Moskow
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}